/**
 * Herb images — AI-generated photographs served from backend.
 */
export const HERB_IMAGES: Record<string, string> = {
  h1:  '/uploads/herbs/人参.png',
  h2:  '/uploads/herbs/枸杞子.png',
  h3:  '/uploads/herbs/黄芪.png',
  h4:  '/uploads/herbs/菊花.png',
  h5:  '/uploads/herbs/干姜.png',
  h6:  '/uploads/herbs/甘草.png',
  h7:  '/uploads/herbs/当归.png',
  h8:  '/uploads/herbs/党参.png',
  h9:  '/uploads/herbs/白术.png',
  h10: '/uploads/herbs/茯苓.png',
  h11: '/uploads/herbs/陈皮.png',
  h12: '/uploads/herbs/半夏.png',
  h13: '/uploads/herbs/麦冬.png',
  h14: '/uploads/herbs/丹参.png',
  h15: '/uploads/herbs/金银花.png',
  h16: '/uploads/herbs/决明子.png',
  h17: '/uploads/herbs/山药.png',
  h18: '/uploads/herbs/熟地黄.png',
  h19: '/uploads/herbs/肉桂.png',
  h20: '/uploads/herbs/酸枣仁.png',
  // Recipes
  r1: '/uploads/recipes/冬日红枣姜糖茶.png',
  r2: '/uploads/recipes/杞菊清肝明目茶.png',
  r3: '/uploads/recipes/黑米红豆健脾粥.png',
  r4: '/uploads/recipes/四神汤.png',
  r5: '/uploads/recipes/当归生姜羊肉汤.png',
  r6: '/uploads/recipes/银耳莲子羹.png',
  r7: '/uploads/recipes/山楂陈皮消食茶.png',
  r8:  '/uploads/recipes/桂圆红枣安神茶.png',
  r9:  '/uploads/recipes/百合雪梨润肺汤.png',
  r10: '/uploads/recipes/薏米赤小豆祛湿粥.png',
  r11: '/uploads/recipes/党参黄芪补气鸡汤.png',
  r12: '/uploads/recipes/菊花决明子降压茶.png',
  r13: '/uploads/recipes/核桃黑芝麻补肾糊.png',
  r14: '/uploads/recipes/酸枣仁茯苓安神粥.png',
  r15: '/uploads/recipes/桑葚枸杞滋阴膏.png',
  r16: '/uploads/recipes/陈皮生姜暖胃饮.png',
  r17: '/uploads/recipes/莲子芡实健脾羹.png',
  r18: '/uploads/recipes/玫瑰花佛手疏肝茶.png',
  r19: '/uploads/recipes/冬瓜薏仁消肿汤.png',
  r20: '/uploads/recipes/黄精首乌养发粥.png',
};
